# application.yml
aws:
  region: ap-northeast-2
management:
  metrics:
    export:
      cloudwatch:
        namespace: MyService
spring:
  kafka:
    bootstrap-servers: b-1.msk.xxx.amazonaws.com:9092

